# -*- mode: ruby -*-
# vi: set ft=ruby :

# https://docs.vagrantup.com
# https://vagrantcloud.com/search

Vagrant.configure("2") do |config|
  config.vm.hostname = "base01"
  #config.vm.base_mac = ""
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.network :private_network, ip: "192.168.33.203"
  config.vm.box_check_update = true
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
    vb.customize ["modifyvm", :id, "--vram", "16"]
    vb.memory = 512
    vb.cpus = "1"
    vb.name = "base01"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
