---
# tasks file for flask_web
- name: Install Flask
  pip:
    name: "{{ flask_installers }}"
    state: present

- name: Copy appy
  copy:
    src: "{{ app_web }}"
    dest: "{{ app_home }}/"

- name: Start Web Server
  shell: FLASK_APP="{{ app_home}}/{{ app_web }}" nohup flask run --host "{{ server_address }}" &